version: '3.8'

services:
  meal-seeker-pg:
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - ${PG_PORT}:${PG_PORT}

  meal-seeker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_PORT: ${PG_PORT}
      PG_HOST: ${PG_HOST}
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - meal-seeker-pg

volumes:
  pg_data: {}
