databases:
  - name: pg
    postgresMajorVersion: 14

services:
  - type: web
    name: api
    env: node
    buildCommand: npm install && npm run build && npm run migration-in-docker:run
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pg
          property: connectionString
      - key: PG_DB
        fromDatabase:
          name: pg
          property: database
