databases:
  - name: meal-seeker-pg
    postgresMajorVersion: 14

services:
  - type: web
    name: meal-seeker-api
    env: node
    buildCommand: npm install && npm run build && npm run migration-in-docker:run
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meal-seeker-pg
          property: connectionString
      - key: PG_DB
        value: db_4ro5
